language: node_js

node_js: 
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12

branches:
  only:
    - master

matrix:
  allow_failures:
    - node_js: 7
    - node_js: 11

install:
  - npm install

script:
  - npm test
  - npm build

notifications:
  email:
    on_success: never
    on_failure: always